annotations:
  licenses: Apache-2.0
apiVersion: v2
name: unguard
version: 0.9.3
description: Unguard is an insecure cloud-native microservices demo application.
type: application
home: https://github.com/dynatrace-oss/unguard
icon: https://github.com/dynatrace-oss/unguard/blob/main/docs/images/logo/unguard-logo-red-small.png
appVersion: 0.9.3
